#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

set -e
set -x

cmd=`jq -r .command config.json`
case "$cmd" in

    dipy_slr)
        cat > script.sh <<EOF
#!/bin/bash
STATIC_TRK=`jq -r '.static_trk' config.json`
if [ $STATIC_TRK == "null" ]; then
    STATIC_TRK=$(pwd)/bundle_atlas_hcp842/Atlas_in_MNI_Space_16_bundles/whole_brain/whole_brain_MNI.trk
fi
dipy_fetch "bundle_atlas_hcp842" --out_dir $(pwd)
$cmd --force \
    --out_dir $(pwd) \
    --x0 $(jq -r .b0_threshold config.json) \
    --rm_small_clusters $(jq -r .b0_threshold config.json) \
    --greater_than $(jq -r .b0_threshold config.json) \
    --less_than $(jq -r .b0_threshold config.json) \
    --nb_pts $(jq -r .b0_threshold config.json) \
    --progressive $(jq -r .b0_threshold config.json) \
    --out_moved "tractogram.trk"
    $STATIC_TRK $(jq -r .moving_tracks config.json) --mix_names
EOF
        ;;
    *)
        echo "invalid command: $cmd"
        exit 1
esac

chmod +x script.sh
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:1.1.1 ./script.sh

echo "done"