#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

export SINGULARITYENV_OMP_NUM_THREADS=7

set -e
set -x

mkdir -p output
chmod -R +w output

PROGRESSIVE=$(jq -r .progressive config.json)

if $PROGRESSIVE
then
    PROGRESSIVE="--progressive"
else
    PROGRESSIVE=""
fi

time singularity exec -e docker://brainlife/dipy:1.1.1 dipy_slr \
    --force \
    --out_dir output \
    --out_moved track.trk \
    --x0 $(jq -r .x0 config.json) \
    --rm_small_clusters $(jq -r .rm_small_clusters config.json) \
    --greater_than $(jq -r .greater_than config.json) \
    --less_than $(jq -r .less_than config.json) \
    --nb_pts $(jq -r .nb_pts config.json) \
    $PROGRESSIVE  \
    $(jq -r .static_track config.json) $(jq -r .moving_track config.json)

echo "done"
